export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const CHECK_TASK_REQUEST = 'CHECK_TASK_REQUEST';
export const CHECK_TASK_SUCCESS = 'CHECK_TASK_SUCCESS';
export const CHECK_TASK_ERROR = 'CHECK_TASK_ERROR';

export const CLEAR_TASKS_REQUEST = 'CLEAR_TASKS_REQUEST';
export const CLEAR_TASKS_SUCCESS = 'CLEAR_TASKS_SUCCESS';
export const CLEAR_TASKS_ERROR = 'CLEAR_TASKS_ERROR';
